name: Docker Hub build

on:
  push:
    branches:
      - carma-develop
      - carma-master
      - "release/*"
    tags:
      - carma-system-*
jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@feature-docker-build-github-submodule
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
    with:
      github_submodules: true
      context: .